export const EXPLORE_OPTIONS = [
  {
    href: '/programs.html',
    name: 'All Programs',
    sub: 'Browse everything in one place',
    cat: 'all',
    all: true,
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.5" /><rect x="14" y="3" width="7" height="7" rx="1.5" /><rect x="3" y="14" width="7" height="7" rx="1.5" /><rect x="14" y="14" width="7" height="7" rx="1.5" /></svg>',
  },
  {
    href: '/tour.html',
    name: 'Tour programs',
    sub: 'Full-day private tours',
    cat: 'tour',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 13l2-6h14l2 6M5 13h14v4H5zM3 13h18" /><circle cx="8" cy="17" r="1.5" /><circle cx="16" cy="17" r="1.5" /></svg>',
  },
  {
    href: '/transfer.html',
    name: 'Transfers',
    sub: 'Airport & area routes',
    cat: 'transfer',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="6" width="18" height="9" rx="2" /><circle cx="7.5" cy="18" r="1.6" /><circle cx="16.5" cy="18" r="1.6" /></svg>',
  },
  {
    href: '/activities.html',
    name: 'Experiences',
    sub: 'ATV, rafting, swing & more',
    cat: 'experience',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v18" /><path d="M5 8c3 0 5 2 7 4 2-2 4-4 7-4" /></svg>',
  },
  {
    href: '/charter.html',
    name: 'Charter',
    sub: 'Car + driver, your route',
    cat: 'charter',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4 17l2-9h12l2 9M2 17h20M9 8V5h6v3" /></svg>',
  },
  {
    href: '/destinations.html',
    name: 'Destinations',
    sub: 'Temples, beaches & rice terraces',
    cat: 'destination',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21s-7-6.2-7-11a7 7 0 0 1 14 0c0 4.8-7 11-7 11z" /><circle cx="12" cy="10" r="2.5" /></svg>',
  },
];
